/**
 * ISO 3166-1 alpha-2 mapping. Used to auto-suggest the ISO2 code when a user
 * types a country name in the admin UI.
 *
 * If a country name does not match any entry here (e.g. alternative spelling),
 * the admin can still type the ISO2 code manually — this map is only a helper.
 */
export interface CountryIsoOption {
  iso: string;
  name: string;
}

export const COUNTRY_ISO2_OPTIONS: CountryIsoOption[] = [
  { iso: "AF", name: "Afghanistan" },
  { iso: "AX", name: "Îles Åland" },
  { iso: "AL", name: "Albanie" },
  { iso: "DZ", name: "Algérie" },
  { iso: "AS", name: "Samoa américaines" },
  { iso: "AD", name: "Andorre" },
  { iso: "AO", name: "Angola" },
  { iso: "AI", name: "Anguilla" },
  { iso: "AQ", name: "Antarctique" },
  { iso: "AG", name: "Antigua-et-Barbuda" },
  { iso: "AR", name: "Argentine" },
  { iso: "AM", name: "Arménie" },
  { iso: "AW", name: "Aruba" },
  { iso: "AU", name: "Australie" },
  { iso: "AT", name: "Autriche" },
  { iso: "AZ", name: "Azerbaïdjan" },
  { iso: "BS", name: "Bahamas" },
  { iso: "BH", name: "Bahreïn" },
  { iso: "BD", name: "Bangladesh" },
  { iso: "BB", name: "Barbade" },
  { iso: "BY", name: "Biélorussie" },
  { iso: "BE", name: "Belgique" },
  { iso: "BZ", name: "Belize" },
  { iso: "BJ", name: "Bénin" },
  { iso: "BM", name: "Bermudes" },
  { iso: "BT", name: "Bhoutan" },
  { iso: "BO", name: "Bolivie" },
  { iso: "BQ", name: "Pays-Bas caribéens" },
  { iso: "BA", name: "Bosnie-Herzégovine" },
  { iso: "BW", name: "Botswana" },
  { iso: "BV", name: "Île Bouvet" },
  { iso: "BR", name: "Brésil" },
  { iso: "IO", name: "Territoire britannique de l'océan Indien" },
  { iso: "BN", name: "Brunéi Darussalam" },
  { iso: "BG", name: "Bulgarie" },
  { iso: "BF", name: "Burkina Faso" },
  { iso: "BI", name: "Burundi" },
  { iso: "KH", name: "Cambodge" },
  { iso: "CM", name: "Cameroun" },
  { iso: "CA", name: "Canada" },
  { iso: "CV", name: "Cap-Vert" },
  { iso: "KY", name: "Îles Caïmans" },
  { iso: "CF", name: "République centrafricaine" },
  { iso: "TD", name: "Tchad" },
  { iso: "CL", name: "Chili" },
  { iso: "CN", name: "Chine" },
  { iso: "CX", name: "Île Christmas" },
  { iso: "CC", name: "Îles Cocos" },
  { iso: "CO", name: "Colombie" },
  { iso: "KM", name: "Comores" },
  { iso: "CG", name: "Congo-Brazzaville" },
  { iso: "CD", name: "Congo-Kinshasa" },
  { iso: "CK", name: "Îles Cook" },
  { iso: "CR", name: "Costa Rica" },
  { iso: "CI", name: "Côte d'Ivoire" },
  { iso: "HR", name: "Croatie" },
  { iso: "CU", name: "Cuba" },
  { iso: "CW", name: "Curaçao" },
  { iso: "CY", name: "Chypre" },
  { iso: "CZ", name: "Tchéquie" },
  { iso: "DK", name: "Danemark" },
  { iso: "DJ", name: "Djibouti" },
  { iso: "DM", name: "Dominique" },
  { iso: "DO", name: "République dominicaine" },
  { iso: "EC", name: "Équateur" },
  { iso: "EG", name: "Égypte" },
  { iso: "SV", name: "Salvador" },
  { iso: "GQ", name: "Guinée équatoriale" },
  { iso: "ER", name: "Érythrée" },
  { iso: "EE", name: "Estonie" },
  { iso: "ET", name: "Éthiopie" },
  { iso: "FK", name: "Îles Malouines" },
  { iso: "FO", name: "Îles Féroé" },
  { iso: "FJ", name: "Fidji" },
  { iso: "FI", name: "Finlande" },
  { iso: "FR", name: "France" },
  { iso: "GF", name: "Guyane française" },
  { iso: "PF", name: "Polynésie française" },
  { iso: "TF", name: "Terres australes françaises" },
  { iso: "GA", name: "Gabon" },
  { iso: "GM", name: "Gambie" },
  { iso: "GE", name: "Géorgie" },
  { iso: "DE", name: "Allemagne" },
  { iso: "GH", name: "Ghana" },
  { iso: "GI", name: "Gibraltar" },
  { iso: "GR", name: "Grèce" },
  { iso: "GL", name: "Groenland" },
  { iso: "GD", name: "Grenade" },
  { iso: "GP", name: "Guadeloupe" },
  { iso: "GU", name: "Guam" },
  { iso: "GT", name: "Guatemala" },
  { iso: "GG", name: "Guernesey" },
  { iso: "GN", name: "Guinée" },
  { iso: "GW", name: "Guinée-Bissau" },
  { iso: "GY", name: "Guyana" },
  { iso: "HT", name: "Haïti" },
  { iso: "HM", name: "Îles Heard-et-MacDonald" },
  { iso: "VA", name: "État de la Cité du Vatican" },
  { iso: "HN", name: "Honduras" },
  { iso: "HK", name: "R.A.S. chinoise de Hong Kong" },
  { iso: "HU", name: "Hongrie" },
  { iso: "IS", name: "Islande" },
  { iso: "IN", name: "Inde" },
  { iso: "ID", name: "Indonésie" },
  { iso: "IR", name: "Iran" },
  { iso: "IQ", name: "Irak" },
  { iso: "IE", name: "Irlande" },
  { iso: "IM", name: "Île de Man" },
  { iso: "IL", name: "Israël" },
  { iso: "IT", name: "Italie" },
  { iso: "JM", name: "Jamaïque" },
  { iso: "JP", name: "Japon" },
  { iso: "JE", name: "Jersey" },
  { iso: "JO", name: "Jordanie" },
  { iso: "KZ", name: "Kazakhstan" },
  { iso: "KE", name: "Kenya" },
  { iso: "KI", name: "Kiribati" },
  { iso: "KP", name: "Corée du Nord" },
  { iso: "KR", name: "Corée du Sud" },
  { iso: "KW", name: "Koweït" },
  { iso: "KG", name: "Kirghizistan" },
  { iso: "LA", name: "Laos" },
  { iso: "LV", name: "Lettonie" },
  { iso: "LB", name: "Liban" },
  { iso: "LS", name: "Lesotho" },
  { iso: "LR", name: "Libéria" },
  { iso: "LY", name: "Libye" },
  { iso: "LI", name: "Liechtenstein" },
  { iso: "LT", name: "Lituanie" },
  { iso: "LU", name: "Luxembourg" },
  { iso: "MO", name: "R.A.S. chinoise de Macao" },
  { iso: "MK", name: "Macédoine" },
  { iso: "MG", name: "Madagascar" },
  { iso: "MW", name: "Malawi" },
  { iso: "MY", name: "Malaisie" },
  { iso: "MV", name: "Maldives" },
  { iso: "ML", name: "Mali" },
  { iso: "MT", name: "Malte" },
  { iso: "MH", name: "Îles Marshall" },
  { iso: "MQ", name: "Martinique" },
  { iso: "MR", name: "Mauritanie" },
  { iso: "MU", name: "Maurice" },
  { iso: "YT", name: "Mayotte" },
  { iso: "MX", name: "Mexique" },
  { iso: "FM", name: "États fédérés de Micronésie" },
  { iso: "MD", name: "Moldavie" },
  { iso: "MC", name: "Monaco" },
  { iso: "MN", name: "Mongolie" },
  { iso: "ME", name: "Monténégro" },
  { iso: "MS", name: "Montserrat" },
  { iso: "MA", name: "Maroc" },
  { iso: "MZ", name: "Mozambique" },
  { iso: "MM", name: "Myanmar (Birmanie)" },
  { iso: "NA", name: "Namibie" },
  { iso: "NR", name: "Nauru" },
  { iso: "NP", name: "Népal" },
  { iso: "NL", name: "Pays-Bas" },
  { iso: "NC", name: "Nouvelle-Calédonie" },
  { iso: "NZ", name: "Nouvelle-Zélande" },
  { iso: "NI", name: "Nicaragua" },
  { iso: "NE", name: "Niger" },
  { iso: "NG", name: "Nigéria" },
  { iso: "NU", name: "Niue" },
  { iso: "NF", name: "Île Norfolk" },
  { iso: "MP", name: "Îles Mariannes du Nord" },
  { iso: "NO", name: "Norvège" },
  { iso: "OM", name: "Oman" },
  { iso: "PK", name: "Pakistan" },
  { iso: "PW", name: "Palaos" },
  { iso: "PS", name: "Territoires palestiniens" },
  { iso: "PA", name: "Panama" },
  { iso: "PG", name: "Papouasie-Nouvelle-Guinée" },
  { iso: "PY", name: "Paraguay" },
  { iso: "PE", name: "Pérou" },
  { iso: "PH", name: "Philippines" },
  { iso: "PN", name: "Îles Pitcairn" },
  { iso: "PL", name: "Pologne" },
  { iso: "PT", name: "Portugal" },
  { iso: "PR", name: "Porto Rico" },
  { iso: "QA", name: "Qatar" },
  { iso: "RE", name: "La Réunion" },
  { iso: "RO", name: "Roumanie" },
  { iso: "RU", name: "Russie" },
  { iso: "RW", name: "Rwanda" },
  { iso: "BL", name: "Saint-Barthélemy" },
  { iso: "SH", name: "Sainte-Hélène" },
  { iso: "KN", name: "Saint-Christophe-et-Niévès" },
  { iso: "LC", name: "Sainte-Lucie" },
  { iso: "MF", name: "Saint-Martin" },
  { iso: "PM", name: "Saint-Pierre-et-Miquelon" },
  { iso: "VC", name: "Saint-Vincent-et-les-Grenadines" },
  { iso: "WS", name: "Samoa" },
  { iso: "SM", name: "Saint-Marin" },
  { iso: "ST", name: "Sao Tomé-et-Principe" },
  { iso: "SA", name: "Arabie saoudite" },
  { iso: "SN", name: "Sénégal" },
  { iso: "RS", name: "Serbie" },
  { iso: "SC", name: "Seychelles" },
  { iso: "SL", name: "Sierra Leone" },
  { iso: "SG", name: "Singapour" },
  { iso: "SX", name: "Saint-Martin (partie néerlandaise)" },
  { iso: "SK", name: "Slovaquie" },
  { iso: "SI", name: "Slovénie" },
  { iso: "SB", name: "Îles Salomon" },
  { iso: "SO", name: "Somalie" },
  { iso: "ZA", name: "Afrique du Sud" },
  { iso: "GS", name: "Géorgie du Sud et îles Sandwich du Sud" },
  { iso: "SS", name: "Soudan du Sud" },
  { iso: "ES", name: "Espagne" },
  { iso: "LK", name: "Sri Lanka" },
  { iso: "SD", name: "Soudan" },
  { iso: "SR", name: "Suriname" },
  { iso: "SJ", name: "Svalbard et Jan Mayen" },
  { iso: "SZ", name: "Eswatini" },
  { iso: "SE", name: "Suède" },
  { iso: "CH", name: "Suisse" },
  { iso: "SY", name: "Syrie" },
  { iso: "TW", name: "Taïwan" },
  { iso: "TJ", name: "Tadjikistan" },
  { iso: "TZ", name: "Tanzanie" },
  { iso: "TH", name: "Thaïlande" },
  { iso: "TL", name: "Timor oriental" },
  { iso: "TG", name: "Togo" },
  { iso: "TK", name: "Tokelau" },
  { iso: "TO", name: "Tonga" },
  { iso: "TT", name: "Trinité-et-Tobago" },
  { iso: "TN", name: "Tunisie" },
  { iso: "TR", name: "Turquie" },
  { iso: "TM", name: "Turkménistan" },
  { iso: "TC", name: "Îles Turques-et-Caïques" },
  { iso: "TV", name: "Tuvalu" },
  { iso: "UG", name: "Ouganda" },
  { iso: "UA", name: "Ukraine" },
  { iso: "AE", name: "Émirats arabes unis" },
  { iso: "GB", name: "Royaume-Uni" },
  { iso: "US", name: "États-Unis" },
  { iso: "UM", name: "Îles mineures éloignées des États-Unis" },
  { iso: "UY", name: "Uruguay" },
  { iso: "UZ", name: "Ouzbékistan" },
  { iso: "VU", name: "Vanuatu" },
  { iso: "VE", name: "Venezuela" },
  { iso: "VN", name: "Vietnam" },
  { iso: "VG", name: "Îles Vierges britanniques" },
  { iso: "VI", name: "Îles Vierges des États-Unis" },
  { iso: "WF", name: "Wallis-et-Futuna" },
  { iso: "EH", name: "Sahara occidental" },
  { iso: "YE", name: "Yémen" },
  { iso: "ZM", name: "Zambie" },
  { iso: "ZW", name: "Zimbabwe" },
  { iso: "IC", name: "Îles Canaries" },
];

/**
 * Common French alternative spellings → canonical name.
 * Extends matching so that PFS/admin country names with alternative spellings
 * still resolve to an ISO2 code.
 */
const NAME_ALIASES: Record<string, string> = {
  "bélarus": "Biélorussie",
  "biélorussie": "Biélorussie",
  "bosnie": "Bosnie-Herzégovine",
  "brunei": "Brunéi Darussalam",
  "cap vert": "Cap-Vert",
  "chypre": "Chypre",
  "république tchèque": "Tchéquie",
  "république tchéque": "Tchéquie",
  "tcheque": "Tchéquie",
  "tchequie": "Tchéquie",
  "republique du congo": "Congo-Brazzaville",
  "republique democratique du congo": "Congo-Kinshasa",
  "les comores": "Comores",
  "el salvador": "Salvador",
  "emirats arabes unis": "Émirats arabes unis",
  "etats unis": "États-Unis",
  "etats unis d amerique": "États-Unis",
  "iles kiribati": "Kiribati",
  "iles samoa": "Samoa",
  "iles turks et caicos": "Îles Turques-et-Caïques",
  "ile maurice": "Maurice",
  "maurice": "Maurice",
  "iles feroe": "Îles Féroé",
  "feroe": "Îles Féroé",
  "iraq": "Irak",
  "birmanie": "Myanmar (Birmanie)",
  "birmanie myanmar": "Myanmar (Birmanie)",
  "myanmar": "Myanmar (Birmanie)",
  "republique federale du nigeria": "Nigéria",
  "nigeria": "Nigéria",
  "niue": "Niue",
  "niué": "Niue",
  "palestine": "Territoires palestiniens",
  "perou": "Pérou",
  "pays bas": "Pays-Bas",
  "macedoine": "Macédoine",
  "reunion": "La Réunion",
  "saint kitts et nevis": "Saint-Christophe-et-Niévès",
  "saint martin": "Saint-Martin",
  "saint martin francais": "Saint-Martin",
  "saint martin neerlandais": "Saint-Martin (partie néerlandaise)",
  "san marin": "Saint-Marin",
  "arabie saoudite": "Arabie saoudite",
  "senegal": "Sénégal",
  "swaziland": "Eswatini",
  "taiwan": "Taïwan",
  "viet nam": "Vietnam",
  "vietnam": "Vietnam",
  "yemen": "Yémen",
  "hong kong": "R.A.S. chinoise de Hong Kong",
  "macao": "R.A.S. chinoise de Macao",
  "vatican": "État de la Cité du Vatican",
  "antilles neerlandaises": "Pays-Bas caribéens",
  "bonaire": "Pays-Bas caribéens",
};

function normalize(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[\s\-'’()]+/g, " ")
    .trim();
}

const NORMALIZED_INDEX: Record<string, string> = (() => {
  const map: Record<string, string> = {};
  for (const { iso, name } of COUNTRY_ISO2_OPTIONS) {
    map[normalize(name)] = iso;
  }
  for (const [alias, canonical] of Object.entries(NAME_ALIASES)) {
    const iso = COUNTRY_ISO2_OPTIONS.find((o) => o.name === canonical)?.iso;
    if (iso) map[normalize(alias)] = iso;
  }
  return map;
})();

/**
 * Suggest an ISO2 code for a country name typed in French.
 * Accent-insensitive, case-insensitive, tolerates punctuation variations and
 * common aliases. Returns null if no match — caller should let the user type
 * the code manually.
 */
export function suggestIso2FromName(name: string | null | undefined): string | null {
  if (!name) return null;
  const key = normalize(name);
  if (!key) return null;
  return NORMALIZED_INDEX[key] ?? null;
}
