/**
 * PFS taxonomy reference data — auto-generated from "Modèle PFS.xlsx" ANNEXE sheets.
 * DO NOT EDIT MANUALLY — run: npx tsx scripts/generate-pfs-taxonomy.ts
 *
 * Used by MarketplaceMappingSection UI + Excel export.
 */

// ── Genre ──

export const PFS_GENDER_LABELS: Record<string, string> = {
  "WOMAN": "Femme",
  "MAN": "Homme",
  "KID": "Enfant",
  "SUPPLIES": "Lifestyle_et_Plus"
};

export function pfsGenderLabel(code: string | null | undefined): string {
  if (!code) return "";
  return PFS_GENDER_LABELS[code] ?? code;
}

// ── Familles par genre ──

export const PFS_FAMILIES_BY_GENDER: Record<string, string[]> = {
  "Femme": [
    "Accessoires",
    "Beauté",
    "Bijoux_Fantaisie",
    "Chaussures",
    "Grandes_Tailles",
    "Lingerie",
    "Maroquinerie",
    "Vêtements"
  ],
  "Homme": [
    "Accessoires_H",
    "Beauté_H",
    "Bijoux_H",
    "Chaussures_H",
    "Maroquinerie_H",
    "Sous_Vêtements",
    "Vêtements_H"
  ],
  "Enfant": [
    "Fille",
    "Garçon",
    "Bébé",
    "Accessoires_K",
    "Maroquinerie_K",
    "Bijoux_Fantaisie_K",
    "Montres_K"
  ],
  "Lifestyle_et_Plus": [
    "Emballages",
    "Fête_et_Décorations",
    "Lifestyle",
    "Matériel_Boutique",
    "Uniformes_Professionnels"
  ]
};

// ── Sous-catégories par famille ──

export const PFS_SUBCATEGORIES_BY_FAMILY: Record<string, string[]> = {
  "Accessoires": [
    "Accessoires",
    "Accessoires de cheveux",
    "Accessoires portable",
    "Bonnets",
    "Casquettes",
    "Ceintures",
    "Chapeaux",
    "Coiffure",
    "Corps",
    "Foulards",
    "Gants",
    "Lunettes",
    "Montres",
    "Parapluies & Ombrelles",
    "Écharpes"
  ],
  "Beauté": [
    "Maquillage",
    "Parfums",
    "Soin du corps"
  ],
  "Bijoux_Fantaisie": [
    "Bagues",
    "Boucles d'oreilles",
    "Bracelets",
    "Broches",
    "Chaînes de cheville",
    "Colliers",
    "Lots avec présentoir",
    "Matériaux bijoux",
    "Parures de bijoux",
    "Pendentifs",
    "Piercings",
    "Présentoirs et rangements nus"
  ],
  "Chaussures": [
    "Babies",
    "Ballerines",
    "Baskets",
    "Bottes",
    "Bottines",
    "Chaussons",
    "Cuissardes",
    "Derbies",
    "Escarpins & Salomés",
    "Espadrilles",
    "Mocassins",
    "Mules & Sabots",
    "Sandales",
    "Tongs"
  ],
  "Grandes_Tailles": [
    "Blazers & Tailleurs",
    "Blouses",
    "Chemises",
    "Combinaisons",
    "Débardeurs",
    "Doudounes",
    "Ensembles",
    "Gilets",
    "Jeans",
    "Jupes",
    "Leggings",
    "Lingeries",
    "Manteaux",
    "Pantacourts",
    "Pantalons",
    "Pulls",
    "Robes",
    "Shorts",
    "Soirées-Cocktails",
    "Tops",
    "T-shirts",
    "Tuniques",
    "Vestes"
  ],
  "Lingerie": [
    "Accessoires",
    "Accessoires de plage",
    "Bas",
    "Bodys",
    "Brassières",
    "Chaussettes",
    "Collants",
    "Culottes",
    "Ensembles de lingerie",
    "Gainants",
    "Maillots de bain",
    "Nuisettes",
    "Peignoirs",
    "Pyjamas",
    "Soutiens-gorge"
  ],
  "Maroquinerie": [
    "Accessoires",
    "Besaces",
    "Bourses",
    "Cabas & Paniers",
    "Petite maroquinerie",
    "Pochettes",
    "Portefeuille",
    "Sacs à dos",
    "Sacs à main",
    "Sacs banane",
    "Sacs bandoulière",
    "Sacs de plage",
    "Sacs épaule",
    "Sacs ordinateur",
    "Sacs transformables",
    "Tote bags"
  ],
  "Vêtements": [
    "Abayas",
    "Blazers & Tailleurs",
    "Blouses",
    "Blousons",
    "Bodys",
    "Capes & Ponchos",
    "Chemises",
    "Combinaisons",
    "Débardeurs & Bustiers",
    "Doudounes",
    "Ensembles",
    "Gilets",
    "Jeans",
    "Jupes",
    "Leggings",
    "Manteaux",
    "Mariage",
    "Pantacourts",
    "Pantalons",
    "Pulls",
    "Robes",
    "Shorts",
    "Soirées-Cocktails",
    "Sport",
    "Sweats",
    "Tops",
    "T-Shirts",
    "Tuniques",
    "Vestes"
  ],
  "Accessoires_H": [
    "Accessoires",
    "Bonnets",
    "Casquettes",
    "Ceintures",
    "Chapeaux",
    "Cravates",
    "Foulards",
    "Gants",
    "Lunettes",
    "Montres",
    "Noeuds papillon",
    "Écharpes"
  ],
  "Beauté_H": [
    "Parfums"
  ],
  "Bijoux_H": [
    "Autres",
    "Bagues",
    "Boucles d'oreilles",
    "Boutons de manchette",
    "Bracelets",
    "Colliers",
    "Pendentifs"
  ],
  "Chaussures_H": [
    "Baskets",
    "Bottines",
    "Chaussons",
    "Derbies",
    "Mocassins",
    "Mules",
    "Richelieu",
    "Sandales",
    "Slip-on",
    "Tennis"
  ],
  "Maroquinerie_H": [
    "Accessoires",
    "Autres",
    "Besaces",
    "Bourses",
    "Cartables",
    "Petite maroquinerie",
    "Pochettes",
    "Porte cartes",
    "Porte passeport",
    "Portefeuille",
    "Reporters",
    "Sacs banane",
    "Sacs bandoulière",
    "Sacs body-bag",
    "Sacs de voyage",
    "Sacs ordinateur",
    "Sacs à dos",
    "Trousses de toilette"
  ],
  "Sous_Vêtements": [
    "Boxers",
    "Chaussettes",
    "Maillots de bain",
    "Pyjamas",
    "Shorts",
    "Slips"
  ],
  "Vêtements_H": [
    "Blazers & Tailleurs",
    "Blousons",
    "Chemises",
    "Costumes",
    "Doudounes",
    "Débardeurs",
    "Ensembles",
    "Gilets",
    "Jeans",
    "Manteaux",
    "Pantacourts",
    "Pantalons",
    "Parka",
    "Polos",
    "Pulls",
    "Shorts et Bermudas",
    "Sport",
    "Sweats",
    "T-shirts",
    "Vestes"
  ],
  "Accessoires_K": [
    "Autres",
    "Bonnets",
    "Chapeaux & Casquettes",
    "Collants & Chaussettes",
    "Gants",
    "Lunettes",
    "Serviettes de plage"
  ],
  "Montres_K": [
    "Montres"
  ],
  "Fille": [
    "Bain",
    "Blousons",
    "Chaussures",
    "Chemises",
    "Combinaisons",
    "Débardeurs",
    "Doudounes",
    "Ensembles",
    "Gilets",
    "Jeans",
    "Jupes",
    "Leggings",
    "Manteaux",
    "Pantalons",
    "Pulls",
    "Pyjamas",
    "Robes",
    "Shorts",
    "Sous-vêtements",
    "Sport",
    "Sweats",
    "Tops",
    "Tricots",
    "T-shirts",
    "Vestes"
  ],
  "Garçon": [
    "Bain",
    "Blousons",
    "Chaussures",
    "Chemises",
    "Costumes",
    "Débardeurs",
    "Doudounes",
    "Ensembles",
    "Gilets",
    "Jeans",
    "Manteaux",
    "Pantalons",
    "Polos",
    "Pulls",
    "Pyjamas",
    "Shorts",
    "Sous-vêtements",
    "Sport",
    "Sweats",
    "T-shirts",
    "Vestes"
  ],
  "Bébé": [
    "Fille",
    "Garçon"
  ],
  "Maroquinerie_K": [
    "Maroquinerie"
  ],
  "Bijoux_Fantaisie_K": [
    "Bijoux Fantaisie"
  ],
  "Emballages": [
    "Boîtes & Pochettes",
    "Sacs"
  ],
  "Fêtes_et_Décorations": [
    "Décorations d'intérieur",
    "Fête"
  ],
  "Lifestyle": [
    "Accessoires portable",
    "Autres",
    "Cigarettes électroniques",
    "Éventails",
    "Parapluies & Ombrelles",
    "Parfums d'intérieurs",
    "Porte-clés",
    "Tatouages",
    "Valises & Bagages"
  ],
  "Matériel_Boutique": [
    "Cintres",
    "Hygiène et entretiens",
    "Mannequins",
    "Matériels divers"
  ],
  "Uniformes_Professionnels": [
    "Accessoires"
  ]
};

// ── Couleurs ──

export const PFS_COLORS: string[] = [
  "Abricot",
  "Abstrait",
  "Acier",
  "ANIMALS",
  "Animaux",
  "Anthracite",
  "Argent",
  "Autre",
  "Autruche",
  "Aztèque",
  "Baroque",
  "Beige",
  "Bicolore",
  "Blanc",
  "Bleu",
  "Bleu Ciel",
  "Bleu Clair",
  "Bleu Foncé",
  "Bleu Irisé",
  "Bleu Océan",
  "Bleu Pétrole",
  "Bleu Roi",
  "Blush",
  "Bordeaux",
  "Brique",
  "Bronze",
  "Brun",
  "Brun Foncé",
  "Cachemire",
  "Camel",
  "Camouflage",
  "CAMOUFLAGE",
  "Caramel",
  "Carbone",
  "Carmin",
  "CARREAUX",
  "Céladon",
  "Chaîne",
  "Champagne",
  "Chevron",
  "Chocolat",
  "Ciel Nocturne",
  "Cœurs",
  "Cognac",
  "Corail",
  "Crême",
  "Crocodile",
  "Cuivre",
  "Cyan",
  "Damier",
  "Denim",
  "Doré",
  "Écru",
  "ETHNIQUE",
  "Étoile",
  "FIGURATIF",
  "Flamant Rose",
  "Framboise",
  "Fruits",
  "Fuchsia",
  "GEOMETRIC",
  "Géométrique",
  "Girafe",
  "Gris",
  "Gris Ardoise",
  "Gris Clair",
  "Gris Foncé",
  "Gris Perle",
  "Gris Souris",
  "Groovy",
  "Gros Pois",
  "Grosses Fleurs",
  "Indigo",
  "Ivoire",
  "Jacquard",
  "Jaune",
  "Jaune Citron",
  "Jaune Clair",
  "Jaune Fluo",
  "Jaune Foncé",
  "Jaune Soleil",
  "Jeans",
  "Kaki",
  "Lavande",
  "Léopard",
  "Lettres",
  "Lilas",
  "Losange",
  "Magenta",
  "Mandala",
  "Marine",
  "Marron Clair",
  "Marron Foncé",
  "Mauve",
  "Messages",
  "Motifs",
  "MOTIFS",
  "Moutarde",
  "Multicolore",
  "MULTICOULEUR",
  "Noir",
  "Noir Irisé",
  "Nude",
  "Ocre",
  "Olive",
  "Or",
  "Orange",
  "Orange Fluo",
  "Petit Pois",
  "Petites Fleurs",
  "Pied de poule",
  "Plume",
  "POIS",
  "Prince de Galles",
  "Prune",
  "Psychédélique",
  "Rayures",
  "Rose",
  "Rose Fluo",
  "Rouge",
  "Rouge Clair",
  "Rouge Foncé",
  "Rouge Orangé",
  "Rouille",
  "Saumon",
  "Serpent",
  "Tartan",
  "Taupe",
  "Terracotta",
  "Tie and dye",
  "Tigre",
  "Transparent",
  "Tropical",
  "Turquoise",
  "TYPOGRAPHIQUE",
  "Vache",
  "Vanille",
  "VEGETATION",
  "Vert",
  "Vert Bouteille",
  "Vert Canard",
  "Vert Clair",
  "Vert d'Eau",
  "Vert Fluo",
  "Vert Foncé",
  "Vert Pomme",
  "Vert Sapin",
  "Vichy",
  "Vieux Rose",
  "VINTAGE",
  "Violet",
  "Wax",
  "Zèbre",
  "Zigzag"
];

// ── Compositions / Matières ──

export const PFS_COMPOSITIONS: string[] = [
  "ABS",
  "Acétate",
  "Acier",
  "Acier inoxydable",
  "Acrylique",
  "Agneau",
  "Alpaga",
  "Aluminium",
  "Angora",
  "Argent 925",
  "Autre",
  "Autruche",
  "Bambou",
  "Bébé alpaca",
  "Bois",
  "Cachemire",
  "Caoutchouc",
  "Carbone",
  "Céramique",
  "Chanvre bio",
  "Chlorofibre",
  "Coquillage",
  "Corde",
  "Coton",
  "Coton bio",
  "Coton de percale",
  "Coton recyclé",
  "Cotton peigné",
  "Cristal",
  "Croûte de cuir",
  "Cuir",
  "Cuir à tannage",
  "Cuir Agneau",
  "Cuir De Mouton",
  "Cuir de vachette",
  "Cuir De Vachette",
  "Cuir de veau",
  "Cuir Pleine Fleur",
  "Cuir végétal",
  "Cuivre",
  "Cupro",
  "Duvet",
  "Econyl",
  "Élasthanne",
  "Fibre d’ortie",
  "Fibre de polyester",
  "Fibre Ingeo",
  "Fil d'aluminium",
  "Fil métallique",
  "Fourrure synthétique",
  "Fourrure véritable",
  "Jute",
  "Kid Mohair",
  "Laine",
  "Laine bio",
  "Laine recyclée",
  "Laiton",
  "Lapin",
  "Lenpur",
  "Liège",
  "Lin",
  "Lin bio",
  "Lurex",
  "Lyocell",
  "Marmotte",
  "Métal",
  "Modal",
  "Mohair",
  "Nacre",
  "Nubuck",
  "Nylon",
  "P.U.",
  "Paille",
  "Papier",
  "PBT",
  "Perle",
  "Perle de culture",
  "Pierre",
  "Pierre naturelle",
  "Plaqué argent",
  "Plaqué or",
  "Plastique",
  "Plexiglass",
  "Plume",
  "Polyacrylique",
  "Polyamide",
  "Polyamide recyclé",
  "Polycarbonate",
  "Polyester",
  "Polyester recyclé",
  "Polypropylène",
  "Polypropylene Recycle",
  "PVC",
  "Raffia",
  "Ramie",
  "Rayonne",
  "Renard",
  "Résine",
  "Rhodium",
  "Silicone",
  "Soie",
  "Strass",
  "Suedine",
  "Super Kid Mohair",
  "Synthétique",
  "Textile",
  "Tissu",
  "Toile",
  "Toile de jute",
  "Verre",
  "Vinyle",
  "Viscose"
];

// ── Pays de fabrication ──

export const PFS_COUNTRIES: string[] = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Anguilla",
  "Antigua-et-Barbuda",
  "Antilles Néerlandaises",
  "Arabie Saoudite",
  "Argentine",
  "Arménie",
  "Aruba",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Bélarus",
  "Belgique",
  "Belize",
  "Bénin",
  "Bermudes",
  "Bhoutan",
  "Birmanie (Myanmar)",
  "Bolivie",
  "Bonaire",
  "Bosnie",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-vert",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Corée du Sud",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Curaçao",
  "Danemark",
  "Djibouti",
  "Dominique",
  "Égypte",
  "El Salvador",
  "Émirats Arabes Unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "États Fédérés de Micronésie",
  "Etats-Unis",
  "Éthiopie",
  "Féroé",
  "Fidji",
  "Finlande",
  "France",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Géorgie du Sud et les Îles Sandwich du Sud",
  "Ghana",
  "Gibraltar",
  "Grèce",
  "Grenade",
  "Groenland",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernesey",
  "Guinée",
  "Guinée Équatoriale",
  "Guinée-Bissau",
  "Guyana",
  "Guyane Française",
  "Haïti",
  "Honduras",
  "Hong Kong",
  "Hongrie",
  "Île Christmas",
  "Île de Man",
  "Ile Maurice",
  "Île Norfolk",
  "Îles Åland",
  "Îles Caïmans",
  "Iles Canaries",
  "Îles Cocos (Keeling)",
  "Îles Cook",
  "Iles Kiribati",
  "Îles Malouines",
  "Îles Mariannes du Nord",
  "Îles Marshall",
  "Îles Pitcairn",
  "Îles Salomon",
  "Iles Samoa",
  "Îles Turks et Caïques",
  "Îles Vierges Britanniques",
  "Inde",
  "Indonésie",
  "Iran",
  "Iraq",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jersey",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kosovo",
  "Koweït",
  "Laos",
  "Les Comores",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Libéria",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macao",
  "Macédoine",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maroc",
  "Martinique",
  "Mauritanie",
  "Mayotte",
  "Mexique",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Montserrat",
  "Mozambique",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niué",
  "Norvège",
  "Nouvelle-Calédonie",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Palestine",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pays-Bas",
  "Perou",
  "Philippines",
  "Pologne",
  "Polynésie Française",
  "Porto Rico",
  "Portugal",
  "Qatar",
  "République Centrafricaine",
  "République Démocratique du Congo",
  "République du Congo",
  "République fédérale du Nigeria",
  "République Tchéque",
  "Réunion",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Saint-Barthélemy",
  "Saint-Kitts-et-Nevis",
  "Saint-Martin (Français)",
  "Saint-Martin (Néerlandais)",
  "Saint-Pierre-Et-Miquelon",
  "Saint-Vincent-et-les Grenadines",
  "Sainte-Lucie",
  "San Marin",
  "Sao Tomé-et-Principe",
  "Senegal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Suriname",
  "Svalbard et Jan Mayen",
  "Swaziland",
  "Syrie",
  "Tadjikistan",
  "Taiwan",
  "Tanzanie",
  "Tchad",
  "Terres Australes Françaises",
  "Thaïlande",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Viet Nam",
  "Wallis et Futuna",
  "Yemen",
  "Zambie",
  "Zimbabwe"
];
